<?php
/**
 * Created by PhpStorm.
 * User: csi0n
 * Date: 3/6/18
 * Time: 7:18 AM
 */

namespace Modules\Frontend\Transformers;


use Illuminate\Http\Resources\Json\Resource;

class CollectionDataTransformer extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}